import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — AgentFlow',
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[var(--surface)]">
      <div className="max-w-3xl mx-auto px-6 py-20">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-[var(--text-secondary)] mb-10">Last updated: February 19, 2026</p>

        <div className="prose prose-invert prose-sm max-w-none space-y-6 text-[var(--text-secondary)] leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-3">1. About AgentFlow</h2>
            <p>
              AgentFlow (&quot;the Service&quot;) is a visual AI agent organization designer operated by Frexida (&quot;we&quot;, &quot;us&quot;).
              The Service allows you to design multi-agent team structures and export configurations for OpenClaw.
            </p>
            <p className="mt-2">
              This Terms of Service applies to the hosted service at
              <a href="https://agentflow.frexida.com" className="text-[var(--accent-bright)] hover:underline">agentflow.frexida.com</a>.
              If you self-host AgentFlow using the open source code, only the
              <a href="https://opensource.org/licenses/MIT" className="text-[var(--accent-bright)] hover:underline" target="_blank" rel="noopener">MIT License</a>
              applies — not this Terms of Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-3">2. Acceptance</h2>
            <p>
              By accessing or using AgentFlow, you agree to these terms. If you don&apos;t agree, please don&apos;t use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-3">3. Accounts</h2>
            <p>
              You can use the editor without an account. Signing in (via GitHub) enables cloud save and additional features.
              You&apos;re responsible for your account security. We use Supabase for authentication and don&apos;t store passwords.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-3">4. Your Data</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Local data</strong> stays in your browser (localStorage). We don&apos;t access it.</li>
              <li><strong>Cloud data</strong> (designs saved after sign-in) is stored in Supabase with Row Level Security. Only you can access your designs.</li>
              <li><strong>API keys</strong> you provide (Anthropic, OpenAI) are encrypted at rest (AES-256-GCM) and used solely to run your Cloud Gateway. We never log or share them.</li>
              <li>You can delete your data at any time from Settings.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-3">5. Ownership of Your Content</h2>
            <p>
              <strong>You retain full ownership</strong> of all content you create using AgentFlow, including:
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Organization designs and agent configurations</li>
              <li>Exported OpenClaw configuration files</li>
              <li>Any outputs generated by your agents</li>
            </ul>
            <p className="mt-3">
              We do not claim any intellectual property rights over your designs or configurations.
              You may use, modify, distribute, or commercialize your content without restriction.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-3">6. Cloud Gateway &amp; API Key Usage</h2>
            <p>
              The Cloud Gateway feature provisions an OpenClaw instance on Fly.io using your API keys.
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>
                <strong>You are responsible for costs incurred with your AI provider</strong> (Anthropic, OpenAI, etc.),
                including charges resulting from agent behavior such as excessive API calls, loops, or unintended usage patterns.
                Any liability for such costs is subject to the limitation of liability in Section 12.
              </li>
              <li>
                We strongly recommend setting <strong>usage limits and spending caps</strong> directly with your AI provider
                before using Cloud Gateway.
              </li>
              <li>
                AgentFlow does not monitor, throttle, or guarantee control over the volume of API calls
                made by agents running on your Gateway.
              </li>
              <li>
                We may suspend or terminate Gateway instances that are idle for extended periods or that
                violate these terms.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-3">7. Acceptable Use</h2>
            <p>Don&apos;t use AgentFlow to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Violate any laws or regulations</li>
              <li>Abuse, overload, or disrupt the Service or its infrastructure</li>
              <li>Attempt to access other users&apos; data</li>
              <li>Use automated tools to scrape or abuse the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-3">8. Account Suspension &amp; Termination</h2>
            <p>
              We may suspend or terminate your account if you:
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Violate these Terms of Service</li>
              <li>Engage in abusive, fraudulent, or illegal activity</li>
              <li>Fail to pay for subscribed services</li>
              <li>Are inactive for an extended period (we will notify you before deletion)</li>
            </ul>
            <p className="mt-2">
              Before termination, we will make reasonable efforts to notify you, explain the reason,
              and provide an opportunity to export your data and contest the decision,
              unless the violation is severe or poses an immediate risk to other users or the Service.
            </p>
            <p className="mt-2">
              You may delete your account at any time from Settings. Upon deletion, all your data
              (designs, API keys, Gateway) will be removed from active systems within 30 days.
              Data in automated backups will be purged as those backups rotate (typically within 90 days).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-3">9. Pricing, Payments &amp; Refunds</h2>
            <p>
              The editor is free and open source (MIT). Paid plans (Pro, Team) provide additional features like cloud save and collaboration.
              Payments are processed through Stripe.
            </p>
            <p className="mt-3"><strong>Cancellation:</strong></p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>You can cancel your subscription at any time from Settings.</li>
              <li>Upon cancellation, you retain access to paid features until the end of your current billing period.</li>
              <li>No prorated refunds are provided for mid-cycle cancellations.</li>
            </ul>
            <p className="mt-3"><strong>Refunds:</strong></p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>We offer a <strong>full refund within 7 days</strong> of your initial subscription if you are not satisfied.</li>
              <li>Refund requests after 7 days are handled on a case-by-case basis.</li>
              <li>To request a refund, contact us via GitHub or email at admin@frexida.com.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-3">10. Open Source &amp; Self-Hosting</h2>
            <p>
              AgentFlow&apos;s source code is available under the MIT License at
              <a href="https://github.com/Frexida/agentflow" className="text-[var(--accent-bright)] hover:underline" target="_blank" rel="noopener">
                github.com/Frexida/agentflow
              </a>.
              Self-hosting is permitted and encouraged. When self-hosted, this Terms of Service does not apply;
              only the MIT License governs your use of the source code.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-3">11. Disclaimers</h2>
            <p>
              The Service is provided &quot;as is&quot; without warranty of any kind. We do not guarantee uptime,
              data preservation, or fitness for any particular purpose.
            </p>
            <p className="mt-2">
              The Service depends on third-party infrastructure (Supabase, Vercel, Fly.io, Stripe) and
              AI providers (Anthropic, OpenAI). We are not responsible for outages, changes, or issues
              caused by these third-party services.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-3">12. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, Frexida&apos;s total aggregate liability
              arising from or related to your use of the Service shall not exceed the greater of:
              (a) the total amount you paid to Frexida in the 12 months preceding the claim, or (b) USD $100.
            </p>
            <p className="mt-2">
              This limitation applies to all claims, whether based on warranty, contract, tort, or any other
              legal theory, including but not limited to costs incurred through third-party AI providers.
              <strong> This limitation does not apply in cases of our intentional misconduct (故意) or gross negligence (重過失).</strong>
            </p>
            <p className="mt-3">
              <strong>Liability Cap:</strong> In any event, our total aggregate liability to you for all claims
              arising from or related to the Service shall not exceed the greater of:
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>The total amount you paid to Frexida in the 12 months preceding the claim, or</li>
              <li>USD $100</li>
            </ul>
            <p className="mt-3">
              <strong>Exception:</strong> This limitation does not apply to damages arising from our gross negligence
              or willful misconduct.
            </p>
            <p className="mt-2">
              Nothing in these terms excludes or limits liability that cannot be excluded or limited under
              applicable law, including the Consumer Contract Act of Japan (消費者契約法) where applicable.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-3">13. Changes</h2>
            <p>
              We may update these terms. Continued use after changes constitutes acceptance.
              Material changes will be announced via the Service or GitHub.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-3">14. Governing Law &amp; Jurisdiction</h2>
            <p>
              These terms are governed by and construed in accordance with the laws of Japan.
              Any disputes arising from or relating to these terms or the Service shall be subject to the
              exclusive jurisdiction of the Tokyo District Court (東京地方裁判所) as the court of first instance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-3">15. Contact</h2>
            <p>
              Questions? Open an issue on{' '}
              <a href="https://github.com/Frexida/agentflow" className="text-[var(--accent-bright)] hover:underline" target="_blank" rel="noopener">
                GitHub
              </a>{' '}
              or email us at{' '}
              <a href="mailto:admin@frexida.com" className="text-[var(--accent-bright)] hover:underline">
                admin@frexida.com
              </a>.
            </p>
          </section>
        </div>
      </div>
    </main>
  )
}
